version: '2'
services:
  api-server:
    build: backend-server/
    ports:
      - '192.168.99.100:8081:8081'
    entrypoint: ['node', 'api-server.js']

  ember: &defaults
    image: danlynn/ember-cli:2.6.2
    volumes:
      - .:/myapp

  npm:
    <<: *defaults
    entrypoint: ['/usr/local/bin/npm']

  bower:
    <<: *defaults
    entrypoint: ['/usr/local/bin/bower', '--allow-root']

  server:
    <<: *defaults
    command: server --watcher polling
    ports:
      - '192.168.99.100:4200:4200'
      - '49152:49152'

  elasticsearch:
    image: elasticsearch:2.3.3
    ports:
      - '192.168.99.100:9200:9200'

  elasticsearch-feed:
    build: elasticsearch-feed/
    depends_on:
      - elasticsearch
    entrypoint: ['./wait_for_elasticsearch.sh', 'elasticsearch', 'node', 'index.js']
